version: "3.9"

services:
  requesthandler:
    build: RequestHandler/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - rabbit
    environment:
      SYNTHETICRABBIT_URL: rabbit

  dbmanager:
    build: DBManager/
    restart: always
    depends_on:
      - db
      - rabbit
    environment:
      DATASOURCE_URL: db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SYNTHETICRABBIT_URL: rabbit

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  rabbit:
    image: rabbitmq
    restart: always